name: qusad_prod_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  visibility_detector: ^0.4.0+2
  sizer: ^3.0.5
  url_launcher: ^6.3.1
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: google_fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: google_fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: google_fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: google_fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: google_fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: google_fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: google_fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/Inter/Inter-Black.ttf
          weight: 900
        - asset: google_fonts/Inter/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: google_fonts/Inter/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: google_fonts/Inter/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: google_fonts/Inter/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: google_fonts/Inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: google_fonts/Inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: google_fonts/Inter/Inter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/Inter/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: google_fonts/Inter/Inter-BlackItalic.ttf
          weight: 900
          style: italic

    - family: JetBrainsMono
      fonts:
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-Light.ttf
          weight: 300
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-Italic.ttf
          weight: 400
          style: italic
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/JetBrains_Mono/JetBrainsMono-ExtraBoldItalic.ttf
          weight: 800
          style: italic

    - family: Manrope
      fonts:
        - asset: google_fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: google_fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: google_fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: google_fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: google_fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: google_fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800

    - family: Raleway
      fonts:
        - asset: google_fonts/Raleway/Raleway-Thin.ttf
          weight: 100
        - asset: google_fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: google_fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: google_fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: google_fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: google_fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: google_fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: google_fonts/Raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: google_fonts/Raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: google_fonts/Raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: google_fonts/Raleway/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: google_fonts/Raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: google_fonts/Raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: google_fonts/Raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/Raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: google_fonts/Raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/
    - assets/images/
    - google_fonts/
    - google_fonts/Inter/
    - google_fonts/JetBrains_Mono/
    - google_fonts/Manrope/
    - google_fonts/Raleway/